name: Build Desktop Packages

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: "false"
      USE_SYSTEM_SIGNTOOL: "true"
      ELECTRON_BUILDER_DISABLE_AUTO_PUBLISH: "true"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WINDOWS_CERT_BASE64: ${{ secrets.WINDOWS_CERT_BASE64 }}
      WINDOWS_CERT_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
      WINDOWS_CERT_DESCRIPTION: ${{ secrets.WINDOWS_CERT_DESCRIPTION }}
      WINDOWS_CERT_TIMESTAMP_URL: ${{ secrets.WINDOWS_CERT_TIMESTAMP_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: 安装依赖
        run: |
          npm install
          npm --prefix frontend install
          go mod download

      - name: 构建 Windows 安装包
        run: npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            dist/*.exe
            dist/*.blockmap

  build-macos:
    runs-on: macos-latest
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: "false"
      ELECTRON_BUILDER_DISABLE_AUTO_PUBLISH: "true"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: 安装依赖
        run: |
          npm install
          npm --prefix frontend install
          go mod download

      - name: 构建 macOS 安装包
        run: npm run dist:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: |
            dist/*.dmg
            dist/*.zip
